defaults:
  - submitit_slurm

timeout_min: 2880  # 2 days
cpus_per_task: 4
mem_gb: 32
partition: owners,gpu
gpus_per_node: 1
setup:
  - ml load cudnn
additional_parameters:
  constraint: '[GPU_MEM:16GB|GPU_MEM:24GB|GPU_MEM:32GB|GPU_MEM:40GB]'
  mail-type: ALL
