name: handwriting
sessions:
  - t5.2019.11.25
  - t5.2019.12.09
  - t5.2019.12.11
  - t5.2019.12.18
  - t5.2019.12.20
  - t5.2020.01.06
datasetToLayerMap: [0, 1, 2, 3, 4, 5]
datasetProbability: [0.16, 0.16, 0.16, 0.16, 0.16, 0.20]
datasetProbabilityVal: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
dataDir:
  - /scratch/groups/shenoy/data/handwriting_data/normalize_with_block_means
  - /oak/stanford/groups/shenoy/stfan/data/handwriting_pseudo_labels/train_11.25/dropout=0.8,seed=9156
  - /oak/stanford/groups/shenoy/stfan/data/handwriting_pseudo_labels/train_12.09_mix_data
  - /oak/stanford/groups/shenoy/stfan/data/handwriting_pseudo_labels/train_12.11_mix_data
  - /oak/stanford/groups/shenoy/stfan/data/handwriting_pseudo_labels/train_12.18_mix_data
  - /oak/stanford/groups/shenoy/stfan/data/handwriting_pseudo_labels/train_12.20_mix_data
syntheticDataDir: /scratch/users/stfan/handwritingBCIData/RNNTrainingSteps/Step3_SyntheticSentences_tf2/HeldOutBlocks
syntheticMixingRate: 0.0
whiteNoiseSD: 1.2
constantOffsetSD: 0.6
randomWalkSD: 0.02
nInputFeatures: 192
timWarpFactor: 0.0
staticGainSD: 0.0
nClasses: 31
maxSeqElements: 500

# Dataset shuffle buffer size
bufferSize: 192

# Copy linear layer 0 to layer 1
copyInputLayer:
  4: 5